# Generated by Django 3.2.4 on 2022-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220113_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('CANCELLED', 'CANCELLED'), ('ACCEPTED', 'ACCEPTED'), ('FINISHED', 'FINISHED')], max_length=10),
        ),
    ]
